source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

use_frameworks!
inhibit_all_warnings!

target 'DashRemote' do
  pod 'TransitionButton', inhibit_warnings: true # SPM support is broken
end

post_install do |installer|
  # Suppress warning "Conversion to Swift 5 is available" from FirebaseFirestoreSwift
  # This removes the warning about swift conversion, hopefuly forever!
  installer.pods_project.root_object.attributes['LastSwiftMigration'] = 9999
  installer.pods_project.root_object.attributes['LastSwiftUpdateCheck'] = 9999
  installer.pods_project.root_object.attributes['LastUpgradeCheck'] = 9999

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Supress warnings:
      # "The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99."
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'

      # Supress warnings:
      # "-pie being ignored. It is only used when linking a main executable"
      # https://stackoverflow.com/a/54786324/784241
      config.build_settings['LD_NO_PIE'] = 'NO'
    end
  end
end
