require 'shellwords'

desc 'Run tests with Xcode'
task :test do
  test = XcodeTest.new(
    scheme: 'Dash',
    device: 'iPad Pro (12.9-inch) (4th generation)',
    ios_version: '13.5'
  )

  test.run(xcpretty: true)
end

desc 'Generate dummy files that are not checked into Git repository but required for build'
task :generate_dummy_resources do
  require 'fileutils'

  [
    'Dash/GoogleService-Info.plist',
    'ShareExtension/GoogleService-Info.plist'
  ].each do |path|
    next if File.exist?(path)
    system('/usr/libexec/PlistBuddy', '-c', 'Save', path)
  end

  [
    'Dash/Sounds/Payment.wav',
    'Dash/Sounds/Share.wav',
    'Dash/Sounds/TollgatePassingThrough.wav'
  ].each do |path|
    next if File.exist?(path)
    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, '')
  end
end

XcodeTest = Struct.new(:scheme, :device, :ios_version, keyword_init: true) do
  def run(xcpretty: true)
    command = build_command.shelljoin

    if xcpretty
      command = "set -o pipefail && #{command} | xcpretty --color"
    end

    system(command) || exit(Process.last_status.exitstatus)
  end

  private

  def build_command
    command = ['xcodebuild']
    command.concat(['-workspace', workspace])
    command.concat(['-scheme', scheme])
    command.concat(['-destination', destination.map { |key, value| "#{key}=#{value}" }.join(',')])
    command << 'test'
    command
  end

  def workspace
    Dir['*.xcworkspace'].first
  end

  def destination
    {
      platform: 'iOS Simulator',
          name: device,
            OS: ios_version
    }
  end
end
